# Generated by Django 3.0.7 on 2022-06-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('identity', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('forms', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('brand_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sale_form', models.CharField(max_length=100)),
                ('unit_quantity', models.FloatField(default=0)),
                ('package_quantity', models.FloatField(default=0)),
                ('drug_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.DrugType')),
            ],
        ),
        migrations.CreateModel(
            name='StockedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_quantity', models.FloatField(default=0)),
                ('package_quantity', models.FloatField(default=0)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('package_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharma.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('unit_quantity', models.FloatField(default=0)),
                ('package_quantity', models.FloatField(default=0)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stocked_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharma.StockedItem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('package_quantity', models.FloatField(blank=True)),
                ('unit_quantity', models.FloatField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharma.StockedItem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
