# Generated by Django 3.0.7 on 2022-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='package_quantity',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='unit_quantity',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='New stock quantity'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
