# Generated by Django 3.0.7 on 2022-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_auto_20220613_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
