# Generated by Django 3.0.7 on 2022-06-26 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharma', '0006_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pharma.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pharma.Sales'),
        ),
    ]
