# Generated by Django 3.0.7 on 2022-08-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0008_auto_20220805_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-date']},
        ),
    ]
