# Generated by Django 3.0.7 on 2022-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0009_auto_20220808_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
