# Generated by Django 3.0.7 on 2022-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0010_auto_20220825_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date (YYYY-MM-DD)'),
        ),
    ]
